apiVersion: batch/v1
kind: Job
metadata:
  name: rayner-bot
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      name: rayner-bot
    spec:
      containers:
      - name: bot
        image: jdob/rayner-bot:latest
        command: ["python", "rayner_bot/runner.py"]
        env:
          - name: HOST
            value: rayner-service
          - name: PORT
            value: "8000"
      restartPolicy: OnFailure
